# Generated by Django 4.2.5 on 2023-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_genrefilmwork_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                through="movies.PersonFilmwork", to="movies.person"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="genrefilmwork",
            unique_together={("film_work", "genre")},
        ),
        migrations.AlterUniqueTogether(
            name="personfilmwork",
            unique_together={("film_work", "person", "role")},
        ),
    ]
