# Generated by Django 4.2.5 on 2023-11-24 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "movies",
            "0003_filmwork_persons_alter_genrefilmwork_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateTimeField(null=True, verbose_name="creation_date"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
