# Generated by Django 4.0.4 on 2023-12-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_filmwork_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "actor"),
                    ("director", "director"),
                    ("writer", "writer"),
                ],
                max_length=255,
                null=True,
                verbose_name="role",
            ),
        ),
    ]
