"""add_cascade_delete_user

Revision ID: 78332a0eea2f
Revises: 4910abd16456
Create Date: 2024-03-07 00:38:25.089122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78332a0eea2f'
down_revision: Union[str, None] = '4910abd16456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'user_data', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_user_id_fkey', 'users', 'user_data', ['user_id'], ['id'])
    # ### end Alembic commands ###
