"""add social netword oauth

Revision ID: 339c0d138f09
Revises: 78332a0eea2f
Create Date: 2024-03-13 00:50:26.214160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339c0d138f09'
down_revision: Union[str, None] = '78332a0eea2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_networks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='User id'),
    sa.Column('social_network_id', sa.String(length=256), nullable=False, comment='Social network user id'),
    sa.Column('social_network_email', sa.String(length=256), nullable=False, comment='Social network user email address'),
    sa.Column('social_networks_name', sa.Enum('yandex', 'vk', 'google', name='socialnetworksnames'), nullable=False, comment='Social networks names'),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.id'], name='mix_social_networks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'social_network_id'),
    sa.UniqueConstraint('social_network_id', 'social_networks_name', name='social_pk'),
    comment='Social networks table'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_networks')
    # ### end Alembic commands ###
