"""add_cascade_delete_histories

Revision ID: 4910abd16456
Revises: 121cf3067241
Create Date: 2024-03-07 00:31:13.786737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4910abd16456'
down_revision: Union[str, None] = '121cf3067241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_history', 'device_id',
               existing_type=sa.VARCHAR(length=256),
               comment='Устройства',
               existing_comment='ID устройства',
               existing_nullable=True)
    op.drop_constraint('auth_history_user_id_fkey', 'auth_history', type_='foreignkey')
    op.create_foreign_key(None, 'auth_history', 'user_data', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_history', type_='foreignkey')
    op.create_foreign_key('auth_history_user_id_fkey', 'auth_history', 'user_data', ['user_id'], ['id'])
    op.alter_column('auth_history', 'device_id',
               existing_type=sa.VARCHAR(length=256),
               comment='ID устройства',
               existing_comment='Устройства',
               existing_nullable=True)
    # ### end Alembic commands ###
