"""alter_auth_history

Revision ID: 5401416ce39f
Revises: 02abff44b630
Create Date: 2024-02-25 19:47:34.183779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5401416ce39f"
down_revision: Union[str, None] = "02abff44b630"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auth_history",
        "dt_logout",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_comment="Дата logout пользователя",
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auth_history",
        "dt_logout",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_comment="Дата logout пользователя",
        existing_server_default=sa.text("timezone('utc'::text, now())"),
    )
    # ### end Alembic commands ###
