"""add_actions_to_roles

Revision ID: 02abff44b630
Revises: 390888ecf4d3
Create Date: 2024-02-25 01:59:46.772739

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.auth_orm_models import MixActionsOrm

# revision identifiers, used by Alembic.
revision: str = "02abff44b630"
down_revision: Union[str, None] = "390888ecf4d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        table=MixActionsOrm.__table__,
        rows=[
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "bb29bca0-a549-4aa7-b75e-39d4ebf648a9",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "d4159fcc-6d65-4281-8303-c2c9cf969a6a",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "6571b7fc-c0b7-42a6-bd86-f673649d074f",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "b9702cdc-a388-4e3c-9176-5da40facc429",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "40869140-b9b1-4665-9af4-efffa6042e09",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "70ddea8f-7c76-4642-a00b-b4f2c4934f17",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "5213525f-b40e-43d5-8252-817987854ccf",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "9641c240-5313-4a49-bb5a-d984eb4678cf",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "e7b1797b-07f1-4b10-8bf6-85c3cfa2dfd0",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "71794196-4df4-4277-82cb-0b2fa17ca60a",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "a56cd0fd-5af8-4fd5-beda-7c7fc9677a18",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "4038c06c-1ef2-411d-bc66-601a3065d38f",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "d7dbf6ad-3c6f-444e-bd38-eb37fd50d642",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "17d6f467-3b59-49eb-bd93-499c69605bb4",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "8995a319-d3b9-46aa-878f-c21d816e4923",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "d91454c4-a706-4d88-8b94-e843ff5021cb",
                "action_id": "3d1ebb54-f05d-4ad1-926c-a4548e1887b4",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "027c5ea6-cd1b-47d4-b87e-66c246fd26ca",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "bb29bca0-a549-4aa7-b75e-39d4ebf648a9",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "d4159fcc-6d65-4281-8303-c2c9cf969a6a",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "6571b7fc-c0b7-42a6-bd86-f673649d074f",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "50c54f3c-2be3-4f0e-a9da-10089e668ac9",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "150c2c89-bc20-4eca-8f1e-1a2c9fef2d65",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "4705bbf9-ddf8-411d-970f-a5fe56911863",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "e03273a9-004c-47e8-9899-a07df741bcf9",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "73d169ee-59f5-44b2-8e5d-85dc8fd20bb4",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "4270b104-38c2-4591-a49b-e5663a970d99",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "9e626c81-1dfd-43d5-87d5-26a35b748e95",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "9e626c81-1dfd-43d5-87d5-26a35b748e95",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "cc96fc52-0077-403d-9810-b34db300a855",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "8f02e288-62db-4499-8457-e8aeb12cadef",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "40869140-b9b1-4665-9af4-efffa6042e09",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "70ddea8f-7c76-4642-a00b-b4f2c4934f17",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "5213525f-b40e-43d5-8252-817987854ccf",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "9641c240-5313-4a49-bb5a-d984eb4678cf",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "e7b1797b-07f1-4b10-8bf6-85c3cfa2dfd0",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "71794196-4df4-4277-82cb-0b2fa17ca60a",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "a56cd0fd-5af8-4fd5-beda-7c7fc9677a18",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "4038c06c-1ef2-411d-bc66-601a3065d38f",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "d7dbf6ad-3c6f-444e-bd38-eb37fd50d642",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "17d6f467-3b59-49eb-bd93-499c69605bb4",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "8995a319-d3b9-46aa-878f-c21d816e4923",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "3d1ebb54-f05d-4ad1-926c-a4548e1887b4",
            },
            {
                "id": uuid.uuid4(),
                "role_id": "25c245c4-1a06-42c7-bb55-0261a2f743d6",
                "action_id": "027c5ea6-cd1b-47d4-b87e-66c246fd26ca",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM mix_actions;"))
    # ### end Alembic commands ###
