"""alter_mix_actions

Revision ID: 8a1bce43ed0d
Revises: 5401416ce39f
Create Date: 2024-02-27 01:55:59.370435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision: str = "8a1bce43ed0d"
down_revision: Union[str, None] = "5401416ce39f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("mix_actions_role_id_fkey", "mix_actions", type_="foreignkey")
    op.create_foreign_key(
        "mix_actions_role_id_fkey",
        "mix_actions",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("mix_actions_role_id_fkey", "mix_actions", type_="foreignkey")
    op.create_foreign_key(
        "mix_actions_role_id_fkey", "mix_actions", "roles", ["role_id"], ["id"]
    )
    # ### end Alembic commands ###
